export const raceKeys: Array<String> = [
  "Human",
  "Ash Hopper",
  "Bear",
  "Boar",
  "Boar (Any)",
  "Boar (Mounted)",
  "Canine",
  "Chaurus",
  "Chaurus Hunter",
  "Chaurus Reaper",
  "Chicken",
  "Cow",
  "Deer",
  "Dog",
  "Dragon Priest",
  "Dragon",
  "Draugr",
  "Dwarven Ballista",
  "Dwarven Centurion",
  "Dwarven Sphere",
  "Dwarven Spider",
  "Falmer",
  "Flame Atronach",
  "Fox",
  "Frost Atronach",
  "Gargoyle",
  "Giant",
  "Goat",
  "Hagraven",
  "Horker",
  "Horse",
  "Ice Wraith",
  "Lurker",
  "Mammoth",
  "Mudcrab",
  "Netch",
  "Rabbit",
  "Riekling",
  "Sabrecat",
  "Seeker",
  "Skeever",
  "Slaughterfish",
  "Storm Atronach",
  "Spider",
  "Large Spider",
  "Giant Spider",
  "Spriggan",
  "Troll",
  "Vampire Lord",
  "Werewolf",
  "Wispmother",
  "Wisp",
  "Wolf"
]