export const raceKeys: Array<String> = [
  "Human",
  "Ash Hopper",
  "Bear",
  "Boar",
  "Boar (Any)",
  "Boar (Mounted)",
  "Canine",
  "Chaurus",
  "Chaurushunter",
  "Chaurusreaper",
  "Chicken",
  "Cow",
  "Deer",
  "Dog",
  "Dragon Priest",
  "Dragon",
  "Draugr",
  "Dwarven Ballista",
  "Dwarven Centurion",
  "Dwarven Sphere",
  "Dwarven Spider",
  "Falmer",
  "Flame Atronach",
  "Foxe",
  "Frost Atronach",
  "Gargoyle",
  "Giant",
  "Goat",
  "Hagraven",
  "Horker",
  "Horse",
  "Ice Wraith",
  "Lurker",
  "Mammoth",
  "Mudcrab",
  "Netche",
  "Rabbit",
  "Riekling",
  "Sabrecat",
  "Seeker",
  "Skeever",
  "Slaughterfish",
  "Storm Atronach",
  "Spider",
  "Large Spider",
  "Giant Spider",
  "Spriggan",
  "Troll",
  "Vampire Lord",
  "Werewolf",
  "Wispmother",
  "Wisp",
  "Wolf"
]