export const tagsNSFW: Array<String> = [
  "69",
  "Anal",
  "Asphyxiation",
  "Blowjob",
  "Boobjob",
  "Breast Sucking",
  "Buttjob",
  "Cowgirl",
  "Cunnilingus",
  "Deepthroat",
  "Doggy",
  "Dominant",
  "Double Penetration",
  "Face Sitting",
  "Facial",
  "Feet",
  "Fingering",
  "Fisting",
  "Footjob",
  "Forced",
  "Gore",
  "Grinding",
  "Handjob",
  "Humiliation",
  "Lead In",
  "Lotus Position",
  "Masturbation",
  "Missionary",
  "Oral",
  "Penetration",
  "Prone Bone",
  "Reverse Cowgirl",
  "Reverse Spitroast",
  "Rimming",
  "Ryona",
  "Spanking",
  "Spitroast",
  "Teasing",
  "Toys",
  "Tribadism",
  "Triple Penetration",
  "Vaginal"
];

export const tagsSFW: Array<String> = [
  "Behind",
  "Facing",
  "Holding",
  "Hugging",
  "Kissing",
  "Kneeling",
  "Loving",
  "Lying",
  "Magic",
  "Sitting",
  "Spooning",
  "Standing"
];
console.assert(tagsNSFW.length + tagsSFW.length < 64);
