export const tagsNSFW: Array<String> = [
  "69",
  "Aggressive",
  "Anal",
  "Asphyxiation",
  "Blowjob",
  "Boobjob",
  "Cowgirl",
  "Cunnilingius",
  "Deepthroat",
  "Doggy",
  "Dominant",
  "Double Penetration",
  "Face Sitting",
  "Feet",
  "Femdom",
  "Footjob",
  "Forced",
  "Gay",
  "Handjob",
  "Lead In",
  "Lesbian",
  "Maledom",
  "Masturbation",
  "Missionary",
  "Oral",
  "Penetration",
  "Reverse Cowgirl",
  "Spitroast",
  "Triple Penetration",
  "Vaginal"
];

export const tagsSFW: Array<String> = [
  "Behind",
  "Facing",
  "Hugging",
  "Kissing",
  "Kneeling",
  "Loving",
  "Lying",
  "Standing"
];
